@extends('layouts.dashboard')

@section('dashboard-title', 'Dashboard Owner')

@section('dashboard-content')
<div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-5 mb-8">
    <div class="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm"><p class="text-xs font-bold uppercase text-slate-400">Pendapatan Hari Ini</p><p class="text-2xl font-black text-emerald-600 mt-2">Rp {{ number_format($dailyRevenue,0,',','.') }}</p></div>
    <div class="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm"><p class="text-xs font-bold uppercase text-slate-400">Pendapatan Bulan Ini</p><p class="text-2xl font-black text-amber-600 mt-2">Rp {{ number_format($monthlyRevenue,0,',','.') }}</p></div>
    <div class="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm"><p class="text-xs font-bold uppercase text-slate-400">Pendapatan Tahun Ini</p><p class="text-2xl font-black text-sky-600 mt-2">Rp {{ number_format($yearlyRevenue,0,',','.') }}</p></div>
    <div class="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm"><p class="text-xs font-bold uppercase text-slate-400">Total Pengunjung Selesai</p><p class="text-2xl font-black text-slate-900 mt-2">{{ number_format($totalVisitors,0,',','.') }}</p></div>
</div>
<div class="grid grid-cols-1 xl:grid-cols-2 gap-6 mb-8">
    <div id="revenue" class="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm"><h2 class="font-bold text-slate-900 mb-5">Grafik Pendapatan Bulanan {{ now()->year }}</h2><div class="space-y-3">@foreach($chartMonths as $i=>$month)@php $value=$chartRevenue[$i]??0; $max=max($chartRevenue->max(),1); @endphp<div class="flex items-center gap-3 text-xs"><span class="w-10 font-bold text-slate-500">{{ $month }}</span><div class="flex-1 h-3 bg-slate-100 rounded-full overflow-hidden"><div class="h-full bg-gradient-to-r from-amber-500 to-emerald-500" style="width: {{ min(100,($value/$max)*100) }}%"></div></div><span class="w-24 text-right font-bold">{{ number_format($value/1000,0,',','.') }}K</span></div>@endforeach</div></div>
    <div class="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm"><h2 class="font-bold text-slate-900 mb-5">Pengunjung 7 Hari Terakhir</h2><div class="space-y-3">@foreach($dailyVisitors as $day)@php $max=max($dailyVisitors->max('value'),1); @endphp<div class="flex items-center gap-3 text-xs"><span class="w-12 font-bold text-slate-500">{{ $day['label'] }}</span><div class="flex-1 h-3 bg-slate-100 rounded-full overflow-hidden"><div class="h-full bg-sky-500" style="width: {{ min(100,($day['value']/$max)*100) }}%"></div></div><span class="w-10 text-right font-bold">{{ $day['value'] }}</span></div>@endforeach</div></div>
</div>
<div id="tickets" class="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden"><div class="px-6 py-5 bg-slate-50/70 border-b border-slate-100"><h2 class="font-bold text-slate-900">Performa Tiket & Transaksi Terbaru</h2></div><div class="grid grid-cols-1 xl:grid-cols-2 gap-0"><div class="p-6 border-b xl:border-b-0 xl:border-r border-slate-100 space-y-3">@foreach($ticketPerformance as $ticket)<div class="flex justify-between items-center p-3 rounded-2xl bg-slate-50"><span class="font-bold text-sm">{{ $ticket->nama_tiket }}</span><span class="text-xs px-2 py-1 rounded-lg bg-amber-100 text-amber-700 font-bold">Terjual {{ $ticket->sold_count ?? 0 }}</span></div>@endforeach</div><div id="laporan" class="p-6 space-y-3">@forelse($recentPayments as $payment)<div class="flex justify-between items-center text-sm border-b border-slate-100 pb-3"><div><p class="font-bold">{{ $payment->pemesanan->user->name }}</p><p class="text-xs text-slate-400">{{ $payment->pemesanan->tiket->nama_tiket }} • {{ optional($payment->tanggal_bayar)->format('d M Y') }}</p></div><span class="font-black text-emerald-600">Rp {{ number_format($payment->jumlah_bayar,0,',','.') }}</span></div>@empty<p class="text-sm text-slate-500">Belum ada transaksi.</p>@endforelse</div></div></div>
@endsection
